### ISSUE TITLE
Can we make docker-client optional?

### ISSUE THREAD

**Issue by wolfv** [conda-forge/oras-py-feedstock#1]
### Comment:

There is no docker-client package (yet) for osx-arm64. Can we maybe make it optional? If we add the version constraint to `run_constraints: [docker-client ==5.1...` this should still force it to the correct version.

**Comment by vsoch** [comment]
The docker client is used for login and collecting config files, and I actually thought the same and have a branch (not pushed) that was trying to do this. If you also think it's a good idea I can take another look / try to see if it's a reasonable thing to do.

**Comment by wolfv** [comment]
I think this is solved :tada:

**Comment by vsoch** [comment]
Thanks!
